/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import clase1conexionbd.Persona;
import clase1conexionbd.controlador.PersonaBD;
import javax.swing.JOptionPane;
import Utilidad.Utilidades;

/**
 *
 * @author joang
 */
public class GestionPersonaV1 extends javax.swing.JFrame {

    private Utilidades utilidades;
    private PersonaBD controladorPersona;

    /**
     * Creates new form GestionPersonaV1
     */
    public GestionPersonaV1() {
        initComponents();
        utilidades = new Utilidades();
        this.setLocationRelativeTo(null);//CENTRAR VENTANA
        controladorPersona = new PersonaBD();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CuerpoRegistro = new javax.swing.JPanel();
        jLabel_cedula = new javax.swing.JLabel();
        jLabel_nombre = new javax.swing.JLabel();
        jLabel_apellidos = new javax.swing.JLabel();
        jLabel_direccion = new javax.swing.JLabel();
        jLabel_telefono = new javax.swing.JLabel();
        jLabel_correo = new javax.swing.JLabel();
        txt_cedula = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_apellidos = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        txt_correo = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_traer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GESTION PERSONA");

        jLabel1.setText("REGITRO PERSONA");

        CuerpoRegistro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel_cedula.setText("CEDULA:");

        jLabel_nombre.setText("NOMBRE:");

        jLabel_apellidos.setText("APELLIDOS");

        jLabel_direccion.setText("DIRECCION:");

        jLabel_telefono.setText("TELEFONO:");

        jLabel_correo.setText("CORREO:");

        txt_cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cedulaActionPerformed(evt);
            }
        });

        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CuerpoRegistroLayout = new javax.swing.GroupLayout(CuerpoRegistro);
        CuerpoRegistro.setLayout(CuerpoRegistroLayout);
        CuerpoRegistroLayout.setHorizontalGroup(
            CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuerpoRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(CuerpoRegistroLayout.createSequentialGroup()
                        .addComponent(jLabel_apellidos)
                        .addGap(18, 18, 18)
                        .addComponent(txt_apellidos))
                    .addGroup(CuerpoRegistroLayout.createSequentialGroup()
                        .addGroup(CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_cedula)
                            .addComponent(jLabel_nombre))
                        .addGroup(CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CuerpoRegistroLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CuerpoRegistroLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(CuerpoRegistroLayout.createSequentialGroup()
                        .addGroup(CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_direccion)
                            .addComponent(jLabel_telefono)
                            .addComponent(jLabel_correo))
                        .addGap(18, 18, 18)
                        .addGroup(CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_direccion)
                            .addComponent(txt_telefono)
                            .addComponent(txt_correo))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        CuerpoRegistroLayout.setVerticalGroup(
            CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuerpoRegistroLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_cedula)
                    .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nombre)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_apellidos)
                    .addComponent(txt_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_direccion)
                    .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_telefono)
                    .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_correo)
                    .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btn_guardar.setText("GUARDAR");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_editar.setText("EDITAR");

        btn_eliminar.setText("ELIMINAR");

        btn_traer.setText("TRAER");
        btn_traer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_traerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btn_guardar)
                .addGap(45, 45, 45)
                .addComponent(btn_editar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_eliminar)
                .addGap(46, 46, 46)
                .addComponent(btn_traer)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(189, 189, 189))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CuerpoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(CuerpoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardar)
                    .addComponent(btn_editar)
                    .addComponent(btn_eliminar)
                    .addComponent(btn_traer))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_traerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_traerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_traerActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed

        if (txt_cedula.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "EL CAMPO CEDULA ESTA VACIO", "ERROR", JOptionPane.ERROR_MESSAGE);
            txt_cedula.requestFocus();//UBICAR EL CURSOR ENFOCAR EN UN CAMPO
            return;

        }
        if (!utilidades.validadorDeCedula(txt_cedula.getText())) {
            JOptionPane.showMessageDialog(rootPane, "LA CEDULA INGRESADA NO ES LA CORRECTA", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (txt_nombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "EL CAMPO NOMBRE ESTA VACIO", "ERROR", JOptionPane.ERROR_MESSAGE);
            txt_nombre.requestFocus();
            return;
        }
        if (txt_apellidos.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "EL CAMPO APELLIDO ESTA VACIO", "ERROR", JOptionPane.ERROR_MESSAGE);
            txt_apellidos.requestFocus();
            return;
        }
        if (txt_direccion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "EL CAMPO DIRECCION ESTA VACIO", "ERROR", JOptionPane.ERROR_MESSAGE);
            txt_direccion.requestFocus();
            return;
        }
        if (txt_telefono.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "EL CAMPO TELEFONO ESTA VACIO", "ERROR", JOptionPane.ERROR_MESSAGE);
            txt_telefono.requestFocus();
            return;
        }
        if (!utilidades.validarNumero(txt_telefono.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Los datos ingresados en el telefono no son validos.", "ERROR", JOptionPane.ERROR_MESSAGE);
            txt_telefono.requestFocus();
            return;
        }
        if (txt_correo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "EL CAMPO CORREO ESTA VACIO", "ERROR", JOptionPane.ERROR_MESSAGE);
            txt_correo.requestFocus();
            return;
        }
        if (!utilidades.ValidarMail(txt_correo.getText())) {
            JOptionPane.showMessageDialog(rootPane, "EL CAMPO CORREO ES INCORRECTO", "ERROR", JOptionPane.ERROR_MESSAGE);
            txt_direccion.requestFocus();
            return;
        }

        Persona persona = new Persona();
        persona.setCedula(txt_cedula.getText());
        persona.setNombre(txt_nombre.getText());
        persona.setApellido(txt_apellidos.getText());
        persona.setDireccion(txt_direccion.getText());
        persona.setCorreo(txt_correo.getText());
        persona.setTelefono(txt_telefono.getText());
        System.out.println(persona.toString());

        if (controladorPersona.registrarPersona(persona)) {
            JOptionPane.showMessageDialog(rootPane, "PERSONA REGISTRADA CON EXITO");
            txt_cedula.setText(" ");
            txt_nombre.setText(" ");
            txt_apellidos.setText(" ");
            txt_direccion.setText(" ");
            txt_telefono.setText(" ");
            txt_correo.setText(" ");
        } else {
            JOptionPane.showMessageDialog(rootPane, "ERROR - NO SE PUEDE AGREGAR A LA PERSONA", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void txt_cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cedulaActionPerformed

    }//GEN-LAST:event_txt_cedulaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionPersonaV1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionPersonaV1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionPersonaV1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionPersonaV1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionPersonaV1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CuerpoRegistro;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_traer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_apellidos;
    private javax.swing.JLabel jLabel_cedula;
    private javax.swing.JLabel jLabel_correo;
    private javax.swing.JLabel jLabel_direccion;
    private javax.swing.JLabel jLabel_nombre;
    private javax.swing.JLabel jLabel_telefono;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
