/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Tablas.ModelTablePersona;
import clase1conexionbd.Persona;
import clase1conexionbd.controlador.PersonaBD;
import javax.swing.JOptionPane;
import Utilidad.Utilidades;
import clase1conexionbd.Proveedores;
import clase1conexionbd.controlador.ProveedoresBD;
import java.util.ArrayList;
import java.util.List;
import Tablas.ComunicacionVistaModeloTablas;
import Tablas.ModelTableProveedores;
import clase1conexionbd.Inventario;
import clase1conexionbd.controlador.InventarioBD;

/**
 *
 * @author joang
 */
public class GestionContable extends javax.swing.JFrame implements ComunicacionVistaModeloTablas {

    private Utilidades utilidades;
    private PersonaBD controladorPersona;
    private Persona personaEditar;

    //creo una variable de tipo persona para hacer uso en los metodos: ELIMINAR, EDITAR
    private Persona persona;
    private GestionPersona gestionPersona;
    //proveedor:
    private Proveedores proveedorEditar;
    private GestionProveedor gestionProveedor;
    private ProveedoresBD controladorProveedor;
    //INVENTARIO
    private Inventario inventarioEditar;    
    private GestionInventario gestionInventario;
    private InventarioBD controladorInventario;

    //TABLA: CREACION DE UN OBJETO DE LA CLASE DE LA TABLA:
    private ModelTablePersona ModelTablePersona;
    private ModelTableProveedores ModelTableProveedores;

    /**
     * Creates new form GestionPersonaV1
     */
    public GestionContable() {
        controladorPersona = new PersonaBD();
        controladorProveedor = new ProveedoresBD();
        //INICIALIZACION DE LA TABLA:
        ModelTablePersona = new ModelTablePersona(controladorPersona.obtenerPersonas(), this);
        ModelTableProveedores = new ModelTableProveedores(controladorProveedor.obtenerProveedores(), this);

        initComponents();
        utilidades = new Utilidades();
        this.setLocationRelativeTo(null);//CENTRAR VENTANA
        gestionPersona = new GestionPersona(txt_cedula, txt_nombre, txt_apellidos, txt_direccion, txt_correo, txt_telefono, utilidades, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        tabGeneral = new javax.swing.JTabbedPane();
        panelClientes = new javax.swing.JPanel();
        CuerpoRegistro = new javax.swing.JPanel();
        jLabel_cedula = new javax.swing.JLabel();
        jLabel_nombre = new javax.swing.JLabel();
        jLabel_apellidos = new javax.swing.JLabel();
        jLabel_direccion = new javax.swing.JLabel();
        jLabel_telefono = new javax.swing.JLabel();
        jLabel_correo = new javax.swing.JLabel();
        txt_cedula = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_apellidos = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        txt_correo = new javax.swing.JTextField();
        jButton_BuscarCedula = new javax.swing.JButton();
        jButton_BuscarTelefono = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btn_traer = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        txtTituloClientes = new javax.swing.JLabel();
        tablaClientes = new javax.swing.JScrollPane();
        modelTablePersona = new javax.swing.JTable();
        lbBuscarCliente = new javax.swing.JLabel();
        comboParametrodeBuqueda = new javax.swing.JComboBox<>();
        txtParametroBusqueda = new javax.swing.JTextField();
        btnBuscarPersona = new javax.swing.JButton();
        panelProveedores = new javax.swing.JPanel();
        txtTituloProveedores = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtRazonSocialProveedor = new javax.swing.JTextField();
        txtRucProveedor = new javax.swing.JTextField();
        txtNombreRepresentanteProveedor = new javax.swing.JTextField();
        txtApellidoRepresentanteProveedor = new javax.swing.JTextField();
        txtTipoActividadProveedor = new javax.swing.JTextField();
        txtTelefonoProveedor = new javax.swing.JTextField();
        txtCorreoProveedor = new javax.swing.JTextField();
        btnGuardarProveedores = new javax.swing.JButton();
        btnEditarProveedores = new javax.swing.JButton();
        btnEliminarProveedores = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProveedores = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        ComboParametroBusquedaProveedor = new javax.swing.JComboBox<>();
        txtParametroBusquedaProveedor = new javax.swing.JTextField();
        btnBuscarProveedor = new javax.swing.JButton();
        panelInventario = new javax.swing.JPanel();
        txtTituloInventario = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtCantidadProductosInventario = new javax.swing.JTextField();
        txtPrecioVentaInventario = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtPrecioCompraInventario = new javax.swing.JTextField();
        txtDescripcionInventario = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCodigoProductoInventario = new javax.swing.JTextField();
        btnGuardarInventario = new javax.swing.JButton();
        btnEditarInventario = new javax.swing.JButton();
        btnEliminarInventario = new javax.swing.JButton();
        panelVenta = new javax.swing.JPanel();
        txtTituloVenta = new javax.swing.JLabel();
        menuGeneral = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenuItem();
        jMenuAccionPersona = new javax.swing.JMenu();
        botonMenuBuscar = new javax.swing.JMenuItem();
        botonMenuGuardar = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        botonMenuEliminar = new javax.swing.JMenuItem();
        jMenuEditar = new javax.swing.JMenu();
        jMenuAcercade = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GESTION PERSONA");

        CuerpoRegistro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel_cedula.setText("CEDULA:");

        jLabel_nombre.setText("NOMBRE:");

        jLabel_apellidos.setText("APELLIDOS");

        jLabel_direccion.setText("DIRECCION:");

        jLabel_telefono.setText("TELEFONO:");

        jLabel_correo.setText("CORREO:");

        txt_cedula.setToolTipText("Ingrese una cedula valida");
        txt_cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cedulaActionPerformed(evt);
            }
        });

        txt_nombre.setToolTipText("");
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });

        txt_telefono.setToolTipText("Ingrese un numero de telefono valido");

        jButton_BuscarCedula.setText("BUSCAR");
        jButton_BuscarCedula.setToolTipText("Buscar persona por cedula");
        jButton_BuscarCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarCedulaActionPerformed(evt);
            }
        });

        jButton_BuscarTelefono.setText("BUSCAR");
        jButton_BuscarTelefono.setToolTipText("Buscar personas por numero de telefono");
        jButton_BuscarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarTelefonoActionPerformed(evt);
            }
        });

        jButton1.setText("LIMPIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_traer.setText("TRAER");
        btn_traer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_traerActionPerformed(evt);
            }
        });

        btn_eliminar.setText("ELIMINAR");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_editar.setText("EDITAR");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_guardar.setText("GUARDAR");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CuerpoRegistroLayout = new javax.swing.GroupLayout(CuerpoRegistro);
        CuerpoRegistro.setLayout(CuerpoRegistroLayout);
        CuerpoRegistroLayout.setHorizontalGroup(
            CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuerpoRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(CuerpoRegistroLayout.createSequentialGroup()
                            .addComponent(jLabel_apellidos)
                            .addGap(18, 18, 18)
                            .addComponent(txt_apellidos))
                        .addGroup(CuerpoRegistroLayout.createSequentialGroup()
                            .addGroup(CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_cedula)
                                .addComponent(jLabel_nombre))
                            .addGroup(CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CuerpoRegistroLayout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addComponent(txt_cedula)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton_BuscarCedula))
                                .addGroup(CuerpoRegistroLayout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addComponent(txt_nombre))))
                        .addGroup(CuerpoRegistroLayout.createSequentialGroup()
                            .addGroup(CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_direccion)
                                .addComponent(jLabel_telefono)
                                .addComponent(jLabel_correo))
                            .addGap(18, 18, 18)
                            .addGroup(CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_direccion)
                                .addComponent(txt_correo)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CuerpoRegistroLayout.createSequentialGroup()
                                    .addComponent(txt_telefono, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton_BuscarTelefono)))))
                    .addGroup(CuerpoRegistroLayout.createSequentialGroup()
                        .addComponent(btn_guardar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_editar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_eliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_traer)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        CuerpoRegistroLayout.setVerticalGroup(
            CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuerpoRegistroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_cedula)
                    .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_BuscarCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nombre)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_apellidos)
                    .addComponent(txt_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_direccion)
                    .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_telefono)
                    .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_BuscarTelefono))
                .addGap(18, 18, 18)
                .addGroup(CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_correo)
                    .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardar)
                    .addComponent(btn_editar)
                    .addComponent(btn_eliminar)
                    .addComponent(btn_traer)
                    .addComponent(jButton1))
                .addGap(179, 179, 179))
        );

        txtTituloClientes.setText("REGISTRO DE PERSONAS");

        modelTablePersona.setModel(ModelTablePersona);
        tablaClientes.setViewportView(modelTablePersona);

        lbBuscarCliente.setText("Buscar Cliente:");

        comboParametrodeBuqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cedula", "Nombre", "Apellidos", "Telefono", "Correo" }));
        comboParametrodeBuqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboParametrodeBuquedaActionPerformed(evt);
            }
        });

        txtParametroBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtParametroBusquedaActionPerformed(evt);
            }
        });
        txtParametroBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtParametroBusquedaKeyReleased(evt);
            }
        });

        btnBuscarPersona.setText("BUSCAR");
        btnBuscarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPersonaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelClientesLayout = new javax.swing.GroupLayout(panelClientes);
        panelClientes.setLayout(panelClientesLayout);
        panelClientesLayout.setHorizontalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(tablaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClientesLayout.createSequentialGroup()
                        .addComponent(lbBuscarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboParametrodeBuqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtParametroBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarPersona)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClientesLayout.createSequentialGroup()
                        .addComponent(CuerpoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClientesLayout.createSequentialGroup()
                        .addComponent(txtTituloClientes)
                        .addGap(275, 275, 275))))
        );
        panelClientesLayout.setVerticalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTituloClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CuerpoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBuscarCliente)
                    .addComponent(comboParametrodeBuqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtParametroBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPersona))
                .addGap(18, 18, 18)
                .addComponent(tablaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabGeneral.addTab("CLIENTES", panelClientes);

        txtTituloProveedores.setText("GESTION DE PROVEEDORES");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("RUC:");

        jLabel2.setText("RAZON SOCIAL:");

        jLabel3.setText("TIPO DE ACTIVIDAD:");

        jLabel4.setText("NOMBRE REPRESENTATE LEGAL:");

        jLabel5.setText("APELLIDO REPRESENTANTE LEGAL:");

        jLabel6.setText("TELEFONO:");

        jLabel7.setText("CORREO:");

        txtRucProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRucProveedorActionPerformed(evt);
            }
        });

        btnGuardarProveedores.setText("GUARDAR");
        btnGuardarProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarProveedoresActionPerformed(evt);
            }
        });

        btnEditarProveedores.setText("EDITAR");
        btnEditarProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarProveedoresActionPerformed(evt);
            }
        });

        btnEliminarProveedores.setText("ELIMINAR");
        btnEliminarProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProveedoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGuardarProveedores)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarProveedores)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarProveedores))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtRazonSocialProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNombreRepresentanteProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtApellidoRepresentanteProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTipoActividadProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtRucProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTelefonoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCorreoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRucProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRazonSocialProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTipoActividadProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombreRepresentanteProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(txtApellidoRepresentanteProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTelefonoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCorreoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditarProveedores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGuardarProveedores)
                        .addComponent(btnEliminarProveedores)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        tablaProveedores.setModel(ModelTableProveedores);
        jScrollPane1.setViewportView(tablaProveedores);

        jLabel8.setText("Buscar Proveedor:");

        ComboParametroBusquedaProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", " " }));
        ComboParametroBusquedaProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboParametroBusquedaProveedorActionPerformed(evt);
            }
        });

        btnBuscarProveedor.setText("BUSCAR");
        btnBuscarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelProveedoresLayout = new javax.swing.GroupLayout(panelProveedores);
        panelProveedores.setLayout(panelProveedoresLayout);
        panelProveedoresLayout.setHorizontalGroup(
            panelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProveedoresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTituloProveedores)
                .addGap(268, 268, 268))
            .addGroup(panelProveedoresLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1))
                    .addGroup(panelProveedoresLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(ComboParametroBusquedaProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtParametroBusquedaProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarProveedor)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelProveedoresLayout.setVerticalGroup(
            panelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProveedoresLayout.createSequentialGroup()
                .addComponent(txtTituloProveedores)
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(panelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ComboParametroBusquedaProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtParametroBusquedaProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarProveedor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        tabGeneral.addTab("PROVEEDORES", panelProveedores);

        txtTituloInventario.setText("REGISTRO DE INVENTARIO");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel13.setText("CANTIDAD DE PRODUCTOS:");

        jLabel12.setText("PRECIO DE VENTA:");

        jLabel11.setText("PRECIO DE COMPRA:");

        jLabel10.setText("DESCRIPCION:");

        jLabel9.setText("CODIGO DE PRODUCTO:");

        btnGuardarInventario.setText("GUARDAR");
        btnGuardarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarInventarioActionPerformed(evt);
            }
        });

        btnEditarInventario.setText("EDITAR");

        btnEliminarInventario.setText("ELIMINAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnGuardarInventario)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarInventario)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarInventario))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCantidadProductosInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtPrecioVentaInventario)
                                .addComponent(txtDescripcionInventario)
                                .addComponent(txtPrecioCompraInventario)
                                .addComponent(txtCodigoProductoInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtCodigoProductoInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtDescripcionInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtPrecioCompraInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtPrecioVentaInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtCantidadProductosInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarInventario)
                    .addComponent(btnGuardarInventario)
                    .addComponent(btnEliminarInventario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelInventarioLayout = new javax.swing.GroupLayout(panelInventario);
        panelInventario.setLayout(panelInventarioLayout);
        panelInventarioLayout.setHorizontalGroup(
            panelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInventarioLayout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(panelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInventarioLayout.createSequentialGroup()
                        .addComponent(txtTituloInventario)
                        .addGap(273, 273, 273))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInventarioLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))))
        );
        panelInventarioLayout.setVerticalGroup(
            panelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTituloInventario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(266, Short.MAX_VALUE))
        );

        tabGeneral.addTab("INVENTARIO", panelInventario);

        txtTituloVenta.setText("REGISTRO DE VENTA");

        javax.swing.GroupLayout panelVentaLayout = new javax.swing.GroupLayout(panelVenta);
        panelVenta.setLayout(panelVentaLayout);
        panelVentaLayout.setHorizontalGroup(
            panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentaLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(txtTituloVenta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelVentaLayout.setVerticalGroup(
            panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTituloVenta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabGeneral.addTab("VENTA", panelVenta);

        jMenuArchivo.setText("Archivo");

        menuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        jMenuArchivo.add(menuSalir);

        jMenuAccionPersona.setText("Accion Persona");

        botonMenuBuscar.setText("Buscar");
        botonMenuBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenuBuscarActionPerformed(evt);
            }
        });
        jMenuAccionPersona.add(botonMenuBuscar);

        botonMenuGuardar.setText("Editar");
        botonMenuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenuGuardarActionPerformed(evt);
            }
        });
        jMenuAccionPersona.add(botonMenuGuardar);

        jMenuItem3.setText("Guardar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuAccionPersona.add(jMenuItem3);

        botonMenuEliminar.setText("Eliminar");
        botonMenuEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenuEliminarActionPerformed(evt);
            }
        });
        jMenuAccionPersona.add(botonMenuEliminar);

        jMenuArchivo.add(jMenuAccionPersona);

        menuGeneral.add(jMenuArchivo);

        jMenuEditar.setText("Editar");
        menuGeneral.add(jMenuEditar);

        jMenuAcercade.setText("Acerca de");

        jMenuItem1.setText("Creador");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuAcercade.add(jMenuItem1);

        menuGeneral.add(jMenuAcercade);

        setJMenuBar(menuGeneral);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabGeneral)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void buscarPersonaPorCedula() {
        Persona persona = controladorPersona.obtenerPersonCedula(txt_cedula.getText());
        if (persona != null) {
            txt_cedula.setText(persona.getCedula());
            txt_nombre.setText(persona.getNombre());
            txt_apellidos.setText(persona.getApellido());
            txt_direccion.setText(persona.getDireccion());
            txt_correo.setText(persona.getCorreo());
            txt_telefono.setText(persona.getTelefono());
        } else {
            JOptionPane.showMessageDialog(rootPane, "NO SE ENCONTRO AL USUARIO CON LA CEDULA ESPECIFICADA", "ERROR", JOptionPane.ERROR_MESSAGE);
            txt_cedula.setText(" ");
            txt_cedula.requestFocus();
        }

    }

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSalirActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JOptionPane.showMessageDialog(rootPane, "HOLA, SOY JOAN CREADOR DE ESTA INTERFAZ <3");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    public void tabla() {
        List<Persona> personasNombre = controladorPersona.obtenerPersonaNombre(txtParametroBusqueda.getText());
        ModelTablePersona.setPersonas(personasNombre);
        ModelTablePersona.fireTableDataChanged();
    }

    private void guardarPersona() {
        if (controladorPersona.obtenerPersonCedula(txt_cedula.getText()) != null) {

            JOptionPane.showMessageDialog(rootPane, "La persona con ese número de cédula ya se encuentra registrada en el sistema.");
        } else {
            Persona personaGuardar = gestionPersona.guardarEditar();
            if (personaGuardar != null) {
                if (controladorPersona.registrarPersona(gestionPersona.guardarEditar())) {
                    JOptionPane.showMessageDialog(rootPane, "PERSONA REGISTRADA CON EXITO");
                    tabla();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "ERROR - NO SE PUEDE AGREGAR A LA PERSONA", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }
        }

    }

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        guardarPersona();

    }//GEN-LAST:event_btn_guardarActionPerformed

    private void editarPersona() {
        controladorPersona.editarPersona(personaEditar);
        if (personaEditar == null) {
            JOptionPane.showMessageDialog(rootPane, "NO HAY UNA PERSONA SELECCIONADA PARA EDITAR");
        }
        Persona personaEditarLocal = gestionPersona.guardarEditar();
        if (personaEditarLocal != null) {
            personaEditarLocal.setIdPersona(personaEditar.getIdPersona());
            controladorPersona.editarPersona(personaEditarLocal);
            JOptionPane.showMessageDialog(rootPane, "PERSONA EDITADA CON EXITO");
            personaEditar = null;
            gestionPersona.limpiarCamposPersona();
        }
    }
    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        editarPersona();
        List<Persona> persona = controladorPersona.obtenerPersonas();
        ModelTablePersona.setPersonas(persona);
        ModelTablePersona.fireTableDataChanged();


    }//GEN-LAST:event_btn_editarActionPerformed
    public void eliminarPersona() {
        //ELIMINACION DE PERSONA:
        //CONDICION EN CASO DE QUE LOS CAMPOS ESTEN VACIOS:
        if (txt_cedula.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "ESPECIFIQUE QUE DESEA ELIMINAR", "ERROR", JOptionPane.ERROR_MESSAGE);
            //CASO CONTRARIO PASA A ELIMINAR LOS DATOS QUE SE ENCUENTREN EN LOS JTXTFIELS:
        } else {
            //MENSAJE DE CONFIRMACION CON SHOW CONFIRM DIALOG CON SI O NO:
            int confirmar = JOptionPane.showConfirmDialog(null, "¿ESTA SEGURO DE ELIMINAR A ESTE USUARIO?", "confirmar salida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            //EN CASO DE QUE LA OPCION SEA SI:
            if (confirmar == JOptionPane.YES_OPTION) {
                //CONTROLADOR QUE SE ENCARGARGA DE ELIMINAR:
                controladorPersona.eliminarPersona(personaEditar);
                JOptionPane.showMessageDialog(rootPane, "USUARIO SELECCIONADO ELIMINADO CON EXITO");
                gestionPersona.limpiarCamposPersona();
                tabla();

            }
            //EN CASO DE QUE LA OPCION SEA NO:
            if (confirmar == JOptionPane.NO_OPTION) {
                gestionPersona.limpiarCamposPersona();
            }
        }
    }
    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        eliminarPersona();

    }//GEN-LAST:event_btn_eliminarActionPerformed


    private void btn_traerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_traerActionPerformed
        List<Persona> ObtenerPersonas = controladorPersona.obtenerPersonas();
        System.out.println("Personas en la base de datos: " + ObtenerPersonas.size());
        personaEditar = ObtenerPersonas.get(ObtenerPersonas.size() - 1);
        System.out.println(personaEditar);
        txt_cedula.setText(personaEditar.getCedula());
        txt_nombre.setText(personaEditar.getNombre());
        txt_apellidos.setText(personaEditar.getApellido());
        txt_direccion.setText(personaEditar.getDireccion());
        txt_telefono.setText(personaEditar.getTelefono());
        txt_correo.setText(personaEditar.getCorreo());
    }//GEN-LAST:event_btn_traerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        gestionPersona.limpiarCamposPersona();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_BuscarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarTelefonoActionPerformed
        Persona persona = controladorPersona.obtenerPersonaTelefono(txt_telefono.getText());
        if (persona != null) {
            txt_cedula.setText(persona.getCedula());
            txt_nombre.setText(persona.getNombre());
            txt_apellidos.setText(persona.getApellido());
            txt_direccion.setText(persona.getDireccion());
            txt_correo.setText(persona.getCorreo());
            txt_telefono.setText(persona.getTelefono());
        } else {
            JOptionPane.showMessageDialog(rootPane, "NO SE ENCONTRO AL USUARIO CON EL NUMERO DE TELEFONO ESPECIFICADO", "ERROR", JOptionPane.ERROR_MESSAGE);
            txt_telefono.setText(" ");
            txt_telefono.requestFocus();
        }
    }//GEN-LAST:event_jButton_BuscarTelefonoActionPerformed

    private void jButton_BuscarCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarCedulaActionPerformed
        buscarPersonaPorCedula();
    }//GEN-LAST:event_jButton_BuscarCedulaActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txt_cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cedulaActionPerformed

    }//GEN-LAST:event_txt_cedulaActionPerformed

    private void botonMenuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenuGuardarActionPerformed
        editarPersona();
    }//GEN-LAST:event_botonMenuGuardarActionPerformed

    private void botonMenuBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenuBuscarActionPerformed
        buscarPersonaPorCedula();
    }//GEN-LAST:event_botonMenuBuscarActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        guardarPersona();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void botonMenuEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenuEliminarActionPerformed
        eliminarPersona();
    }//GEN-LAST:event_botonMenuEliminarActionPerformed

    private void btnBuscarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPersonaActionPerformed
        //MEQUEDO AQUI!!!!!!!!!------------------------------------------
        if (comboParametrodeBuqueda.getSelectedItem().equals("Cedula")) {
            List<Persona> personas = new ArrayList<>();
            personas.add(controladorPersona.obtenerPersonCedula(txtParametroBusqueda.getText()));
            ModelTablePersona.setPersonas(personas);
            ModelTablePersona.fireTableDataChanged();

        }
        if (comboParametrodeBuqueda.getSelectedItem().equals("Nombre")) {
            List<Persona> personaNombre = controladorPersona.obtenerPersonaNombre(txtParametroBusqueda.getText());
            ModelTablePersona.setPersonas(personaNombre);
            ModelTablePersona.fireTableDataChanged();

        }
        if (comboParametrodeBuqueda.getSelectedItem().equals("Apellidos")) {
            List<Persona> personaApellidos = controladorPersona.obtenerPersonaApellidos(txtParametroBusqueda.getText());
            ModelTablePersona.setPersonas(personaApellidos);
            ModelTablePersona.fireTableDataChanged();
        }

        if (comboParametrodeBuqueda.getSelectedItem().equals("Telefono")) {
            List<Persona> personaTelefono = controladorPersona.obtenerPersonaTelefono1(txtParametroBusqueda.getText());
            ModelTablePersona.setPersonas(personaTelefono);
            ModelTablePersona.fireTableDataChanged();
        }

        if (comboParametrodeBuqueda.getSelectedItem().equals("Correo")) {
            List<Persona> personaCorreo = controladorPersona.obtenerPersonaCorreo(txtParametroBusqueda.getText());
            ModelTablePersona.setPersonas(personaCorreo);
            ModelTablePersona.fireTableDataChanged();
        }
    }//GEN-LAST:event_btnBuscarPersonaActionPerformed

    private void comboParametrodeBuquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboParametrodeBuquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboParametrodeBuquedaActionPerformed

    private void txtParametroBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtParametroBusquedaKeyReleased
//AQUIE CODIGO DE TECLEADO RAPIDO
    }//GEN-LAST:event_txtParametroBusquedaKeyReleased

    private void txtParametroBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtParametroBusquedaActionPerformed

    }//GEN-LAST:event_txtParametroBusquedaActionPerformed

    private void txtRucProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRucProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRucProveedorActionPerformed

    private void btnGuardarProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarProveedoresActionPerformed
        Proveedores proveedores = new Proveedores();
        proveedores.setRuc(txtRucProveedor.getText());
        proveedores.setRazonSocial(txtRazonSocialProveedor.getText());
        proveedores.setTipoActividad(txtTipoActividadProveedor.getText());
        proveedores.setNombreRepresentateLegal(txtNombreRepresentanteProveedor.getText());
        proveedores.setApellidoRepresentanteLegal(txtApellidoRepresentanteProveedor.getText());
        proveedores.setTelefono(txtTelefonoProveedor.getText());
        proveedores.setCorreo(txtCorreoProveedor.getText());
        if (controladorProveedor.registrarProveedor(proveedores)) {
            JOptionPane.showMessageDialog(rootPane, "PROVEEDOR GUARDADO CON EXITO EN EL SISTEMA");
            limpiarCamposProveedor();
            //ACTUALIZAR TABLA PROVEEDORES:
            ModelTableProveedores.setProveedores(controladorProveedor.obtenerProveedores());
            ModelTableProveedores.fireTableDataChanged();

        } else {
            JOptionPane.showMessageDialog(rootPane, "ERROR - NO SE PUEDE AGREGAR AL PROVEEDOR", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnGuardarProveedoresActionPerformed

    void limpiarCamposProveedor() {
        txtRucProveedor.setText(" ");
        txtRazonSocialProveedor.setText(" ");
        txtTipoActividadProveedor.setText("");
        txtNombreRepresentanteProveedor.setText("");
        txtApellidoRepresentanteProveedor.setText("");
        txtTelefonoProveedor.setText("");
        txtCorreoProveedor.setText("");

    }

    private void editarProveedor() {
        controladorProveedor.editarProveedor(proveedorEditar);
        Proveedores proveedorEditarLocal = gestionProveedor.guardarEditarProveedor();
        if (proveedorEditar != null) {
            proveedorEditar.setIdProveedores(proveedorEditar.getIdProveedores());
            controladorProveedor.editarProveedor(proveedorEditarLocal);
            JOptionPane.showMessageDialog(rootPane, "PERSONA EDITADA CON EXITO");
            proveedorEditar = null;
            limpiarCamposProveedor();
        }
    }
    private void btnEditarProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProveedoresActionPerformed
        editarProveedor();
//        List<Proveedores> proveedor = controladorProveedor.obtenerProveedores();
//        ModelTableProveedores.setProveedores(proveedor);
//        ModelTableProveedores.fireTableDataChanged();
    }//GEN-LAST:event_btnEditarProveedoresActionPerformed

    public void tablaProveedores() {
        List<Proveedores> proveedoresNombre = controladorProveedor.obtenerProveedorNombre(txtParametroBusquedaProveedor.getText());
        ModelTableProveedores.setProveedores(proveedoresNombre);
        ModelTableProveedores.fireTableDataChanged();

    }

    public void eliminarProveedor() {
        if (txtRucProveedor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "ESPECIFIQUE QUE DESEA ELIMINAR", "ERROR", JOptionPane.ERROR_MESSAGE);
            //CASO CONTRARIO PASA A ELIMINAR LOS DATOS QUE SE ENCUENTREN EN LOS JTXTFIELS:
        } else {
            //MENSAJE DE CONFIRMACION CON SHOW CONFIRM DIALOG CON SI O NO:
            int confirmar = JOptionPane.showConfirmDialog(null, "¿ESTA SEGURO DE ELIMINAR A ESTE USUARIO?", "confirmar salida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            //EN CASO DE QUE LA OPCION SEA SI:
            if (confirmar == JOptionPane.YES_OPTION) {
                //CONTROLADOR QUE SE ENCARGARGA DE ELIMINAR:
                controladorProveedor.eliminarProveedor(proveedorEditar);
                JOptionPane.showMessageDialog(rootPane, "USUARIO SELECCIONADO ELIMINADO CON EXITO");
                limpiarCamposProveedor();
                tablaProveedores();

            }
            //EN CASO DE QUE LA OPCION SEA NO:
            if (confirmar == JOptionPane.NO_OPTION) {
                limpiarCamposProveedor();
            }
        }

    }


    private void btnEliminarProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProveedoresActionPerformed
        eliminarProveedor();

    }//GEN-LAST:event_btnEliminarProveedoresActionPerformed

    private void ComboParametroBusquedaProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboParametroBusquedaProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboParametroBusquedaProveedorActionPerformed

    private void btnBuscarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProveedorActionPerformed
        if (ComboParametroBusquedaProveedor.getSelectedItem().equals("Nombre")) {
            List<Proveedores> proveedor = new ArrayList<>();
            proveedor.add(controladorProveedor.obtenerProveedoNombre(txtParametroBusquedaProveedor.getText()));
            ModelTableProveedores.setProveedores(proveedor);
            ModelTableProveedores.fireTableDataChanged();
        }
    }//GEN-LAST:event_btnBuscarProveedorActionPerformed
    public void limpiarCamposInventario() {
        txtCodigoProductoInventario.setText("");
        txtDescripcionInventario.setText("");
        txtPrecioCompraInventario.setText("");
        txtPrecioVentaInventario.setText("");
        txtCantidadProductosInventario.setText("");

    }

    private void guardarInventario() {
        Inventario inventario = new Inventario();
        inventario.setCodigoPro(txtCodigoProductoInventario.getText());
        inventario.setDescripcion(txtDescripcionInventario.getText());
        inventario.setPreciosCompra(txtPrecioVentaInventario.getText());
        inventario.setPreciosVenta(txtPrecioVentaInventario.getText());
        inventario.setCantProductos(txtCantidadProductosInventario.getText());
        if (controladorInventario.registrarInventario(inventario)) {
            JOptionPane.showMessageDialog(rootPane, "INVENTARIO GUARDADO CON EXITO EN EL SISTEMA");
            limpiarCamposInventario();
            //ACTUALIZAR TABLA PROVEEDORES:
//            ModelTableProveedores.setProveedores(controladorProveedor.obtenerProveedores());
//            ModelTableProveedores.fireTableDataChanged();

        } else {
            JOptionPane.showMessageDialog(rootPane, "ERROR - NO SE PUEDE AGREGAR AL PROVEEDOR", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void btnGuardarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarInventarioActionPerformed
        guardarInventario();
    }//GEN-LAST:event_btnGuardarInventarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionContable.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionContable.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionContable.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionContable.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionContable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboParametroBusquedaProveedor;
    private javax.swing.JPanel CuerpoRegistro;
    private javax.swing.JMenuItem botonMenuBuscar;
    private javax.swing.JMenuItem botonMenuEliminar;
    private javax.swing.JMenuItem botonMenuGuardar;
    private javax.swing.JButton btnBuscarPersona;
    private javax.swing.JButton btnBuscarProveedor;
    private javax.swing.JButton btnEditarInventario;
    private javax.swing.JButton btnEditarProveedores;
    private javax.swing.JButton btnEliminarInventario;
    private javax.swing.JButton btnEliminarProveedores;
    private javax.swing.JButton btnGuardarInventario;
    private javax.swing.JButton btnGuardarProveedores;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_traer;
    private javax.swing.JComboBox<String> comboParametrodeBuqueda;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_BuscarCedula;
    private javax.swing.JButton jButton_BuscarTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_apellidos;
    private javax.swing.JLabel jLabel_cedula;
    private javax.swing.JLabel jLabel_correo;
    private javax.swing.JLabel jLabel_direccion;
    private javax.swing.JLabel jLabel_nombre;
    private javax.swing.JLabel jLabel_telefono;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenuAccionPersona;
    private javax.swing.JMenu jMenuAcercade;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuEditar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbBuscarCliente;
    private javax.swing.JMenuBar menuGeneral;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JTable modelTablePersona;
    private javax.swing.JPanel panelClientes;
    private javax.swing.JPanel panelInventario;
    private javax.swing.JPanel panelProveedores;
    private javax.swing.JPanel panelVenta;
    private javax.swing.JTabbedPane tabGeneral;
    private javax.swing.JScrollPane tablaClientes;
    private javax.swing.JTable tablaProveedores;
    private javax.swing.JTextField txtApellidoRepresentanteProveedor;
    private javax.swing.JTextField txtCantidadProductosInventario;
    private javax.swing.JTextField txtCodigoProductoInventario;
    private javax.swing.JTextField txtCorreoProveedor;
    private javax.swing.JTextField txtDescripcionInventario;
    private javax.swing.JTextField txtNombreRepresentanteProveedor;
    private javax.swing.JTextField txtParametroBusqueda;
    private javax.swing.JTextField txtParametroBusquedaProveedor;
    private javax.swing.JTextField txtPrecioCompraInventario;
    private javax.swing.JTextField txtPrecioVentaInventario;
    private javax.swing.JTextField txtRazonSocialProveedor;
    private javax.swing.JTextField txtRucProveedor;
    private javax.swing.JTextField txtTelefonoProveedor;
    private javax.swing.JTextField txtTipoActividadProveedor;
    private javax.swing.JLabel txtTituloClientes;
    private javax.swing.JLabel txtTituloInventario;
    private javax.swing.JLabel txtTituloProveedores;
    private javax.swing.JLabel txtTituloVenta;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables

    @Override
    public void clickPersona(Persona p) {
        //System.out.println("Persona " + p.toString());
        txt_cedula.setText(p.getCedula());
        txt_nombre.setText(p.getNombre());
        txt_apellidos.setText(p.getApellido());
        txt_direccion.setText(p.getDireccion());
        txt_telefono.setText(p.getTelefono());
        txt_correo.setText(p.getCorreo());
        personaEditar = p;
        persona = p;

    }

    @Override
    public void clickProveedores(Proveedores p) {
        txtRucProveedor.setText(p.getRuc());
        txtRazonSocialProveedor.setText(p.getRazonSocial());
        txtTipoActividadProveedor.setText(p.getTipoActividad());
        txtNombreRepresentanteProveedor.setText(p.getNombreRepresentateLegal());
        txtApellidoRepresentanteProveedor.setText(p.getApellidoRepresentanteLegal());
        txtTelefonoProveedor.setText(p.getTelefono());
        txtCorreoProveedor.setText(p.getCorreo());
        proveedorEditar = p;

    }
}
