/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import clase1conexionbd.Persona;
import clase1conexionbd.controlador.PersonaBD;
import javax.swing.JOptionPane;
import Utilidad.Utilidades;
import java.util.List;

/**
 *
 * @author joang
 */
public class GestionPersonaV1 extends javax.swing.JFrame {

    private Utilidades utilidades;
    private PersonaBD controladorPersona;
    private Persona personaEditar;
    //creo una variable de tipo persona para hacer uso en los metodos: ELIMINAR, EDITAR
    private Persona persona;

    /**
     * Creates new form GestionPersonaV1
     */
    public GestionPersonaV1() {
        initComponents();
        utilidades = new Utilidades();
        this.setLocationRelativeTo(null);//CENTRAR VENTANA
        controladorPersona = new PersonaBD();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CuerpoRegistro = new javax.swing.JPanel();
        jLabel_cedula = new javax.swing.JLabel();
        jLabel_nombre = new javax.swing.JLabel();
        jLabel_apellidos = new javax.swing.JLabel();
        jLabel_direccion = new javax.swing.JLabel();
        jLabel_telefono = new javax.swing.JLabel();
        jLabel_correo = new javax.swing.JLabel();
        txt_cedula = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_apellidos = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        txt_correo = new javax.swing.JTextField();
        jButton_BuscarCedula = new javax.swing.JButton();
        jButton_BuscarTelefono = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_traer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GESTION PERSONA");

        jLabel1.setText("REGITRO PERSONA");

        CuerpoRegistro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel_cedula.setText("CEDULA:");

        jLabel_nombre.setText("NOMBRE:");

        jLabel_apellidos.setText("APELLIDOS");

        jLabel_direccion.setText("DIRECCION:");

        jLabel_telefono.setText("TELEFONO:");

        jLabel_correo.setText("CORREO:");

        txt_cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cedulaActionPerformed(evt);
            }
        });

        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });

        jButton_BuscarCedula.setText("BUSCAR");
        jButton_BuscarCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarCedulaActionPerformed(evt);
            }
        });

        jButton_BuscarTelefono.setText("BUSCAR");
        jButton_BuscarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarTelefonoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CuerpoRegistroLayout = new javax.swing.GroupLayout(CuerpoRegistro);
        CuerpoRegistro.setLayout(CuerpoRegistroLayout);
        CuerpoRegistroLayout.setHorizontalGroup(
            CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuerpoRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(CuerpoRegistroLayout.createSequentialGroup()
                        .addComponent(jLabel_apellidos)
                        .addGap(18, 18, 18)
                        .addComponent(txt_apellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE))
                    .addGroup(CuerpoRegistroLayout.createSequentialGroup()
                        .addGroup(CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_cedula)
                            .addComponent(jLabel_nombre))
                        .addGroup(CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CuerpoRegistroLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_BuscarCedula))
                            .addGroup(CuerpoRegistroLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(txt_nombre))))
                    .addGroup(CuerpoRegistroLayout.createSequentialGroup()
                        .addGroup(CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_direccion)
                            .addComponent(jLabel_telefono)
                            .addComponent(jLabel_correo))
                        .addGap(18, 18, 18)
                        .addGroup(CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_direccion)
                            .addComponent(txt_correo)
                            .addGroup(CuerpoRegistroLayout.createSequentialGroup()
                                .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_BuscarTelefono)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        CuerpoRegistroLayout.setVerticalGroup(
            CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuerpoRegistroLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_cedula)
                    .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_BuscarCedula))
                .addGap(18, 18, 18)
                .addGroup(CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nombre)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_apellidos)
                    .addComponent(txt_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_direccion)
                    .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_telefono)
                    .addGroup(CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_BuscarTelefono)))
                .addGap(18, 18, 18)
                .addGroup(CuerpoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_correo)
                    .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btn_guardar.setText("GUARDAR");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_editar.setText("EDITAR");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_eliminar.setText("ELIMINAR");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_traer.setText("TRAER");
        btn_traer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_traerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btn_guardar)
                .addGap(45, 45, 45)
                .addComponent(btn_editar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_eliminar)
                .addGap(46, 46, 46)
                .addComponent(btn_traer)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(189, 189, 189))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CuerpoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(CuerpoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardar)
                    .addComponent(btn_editar)
                    .addComponent(btn_eliminar)
                    .addComponent(btn_traer))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_traerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_traerActionPerformed
        List<Persona> ObtenerPersonas = controladorPersona.obtenerPersonas();
        System.out.println("Personas en la base de datos: " + ObtenerPersonas.size());
        personaEditar = ObtenerPersonas.get(ObtenerPersonas.size() - 1);
        System.out.println(personaEditar);
        txt_cedula.setText(personaEditar.getCedula());
        txt_nombre.setText(personaEditar.getNombre());
        txt_apellidos.setText(personaEditar.getApellido());
        txt_direccion.setText(personaEditar.getDireccion());
        txt_telefono.setText(personaEditar.getTelefono());
        txt_correo.setText(personaEditar.getCorreo());


    }//GEN-LAST:event_btn_traerActionPerformed
    private void limpiar() {
        txt_cedula.setText(" ");
        txt_nombre.setText(" ");
        txt_apellidos.setText(" ");
        txt_direccion.setText(" ");
        txt_telefono.setText(" ");
        txt_correo.setText(" ");

    }
    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        if (controladorPersona.obtenerPersonCedula(txt_cedula.getText()) != null) {

            JOptionPane.showMessageDialog(rootPane, "La persona con ese número de cédula ya se encuentra registrada en el sistema.");
        } else {
            Persona personaGuardar = guardarEditar();
            if (personaGuardar != null) {
                if (controladorPersona.registrarPersona(guardarEditar())) {
                    JOptionPane.showMessageDialog(rootPane, "PERSONA REGISTRADA CON EXITO");
                    limpiar();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "ERROR - NO SE PUEDE AGREGAR A LA PERSONA", "ERROR", JOptionPane.ERROR_MESSAGE);
                }

    }//GEN-LAST:event_btn_guardarActionPerformed
        }
    }
    private void txt_cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cedulaActionPerformed

    }//GEN-LAST:event_txt_cedulaActionPerformed

    public Persona guardarEditar() {
        if (txt_cedula.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "EL CAMPO CEDULA ESTA VACIO", "ERROR", JOptionPane.ERROR_MESSAGE);
            txt_cedula.requestFocus();//UBICAR EL CURSOR ENFOCAR EN UN CAMPO
            return null;

        }
        if (!utilidades.validadorDeCedula(txt_cedula.getText())) {
            JOptionPane.showMessageDialog(rootPane, "LA CEDULA INGRESADA NO ES LA CORRECTA", "ERROR", JOptionPane.ERROR_MESSAGE);
            return null;
        }

        if (txt_nombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "EL CAMPO NOMBRE ESTA VACIO", "ERROR", JOptionPane.ERROR_MESSAGE);
            txt_nombre.requestFocus();
            return null;
        }
        if (txt_apellidos.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "EL CAMPO APELLIDO ESTA VACIO", "ERROR", JOptionPane.ERROR_MESSAGE);
            txt_apellidos.requestFocus();
            return null;
        }
        if (txt_direccion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "EL CAMPO DIRECCION ESTA VACIO", "ERROR", JOptionPane.ERROR_MESSAGE);
            txt_direccion.requestFocus();
            return null;
        }
        if (txt_telefono.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "EL CAMPO TELEFONO ESTA VACIO", "ERROR", JOptionPane.ERROR_MESSAGE);
            txt_telefono.requestFocus();
            return null;
        }
        if (!utilidades.validarNumero(txt_telefono.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Los datos ingresados en el telefono no son validos.", "ERROR", JOptionPane.ERROR_MESSAGE);
            txt_telefono.requestFocus();
            return null;
        }
        if (txt_correo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "EL CAMPO CORREO ESTA VACIO", "ERROR", JOptionPane.ERROR_MESSAGE);
            txt_correo.requestFocus();
            return null;
        }
        if (!utilidades.ValidarMail(txt_correo.getText())) {
            JOptionPane.showMessageDialog(rootPane, "EL CAMPO CORREO ES INCORRECTO", "ERROR", JOptionPane.ERROR_MESSAGE);
            txt_direccion.requestFocus();
            return null;
        }

        Persona persona = new Persona();
        persona.setCedula(txt_cedula.getText());
        persona.setNombre(txt_nombre.getText());
        persona.setApellido(txt_apellidos.getText());
        persona.setDireccion(txt_direccion.getText());
        persona.setCorreo(txt_correo.getText());
        persona.setTelefono(txt_telefono.getText());
        System.out.println(persona.toString());
        return persona;

    }

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        controladorPersona.editarPersona(personaEditar);
        if (personaEditar == null) {
            JOptionPane.showMessageDialog(rootPane, "NO HAY UNA PERSONA SELECCIONADA PARA EDITAR");

        }
        Persona personaEditarLocal = guardarEditar();
        if (personaEditarLocal != null) {
            personaEditarLocal.setIdPersona(personaEditar.getIdPersona());
            controladorPersona.editarPersona(personaEditarLocal);
            JOptionPane.showMessageDialog(rootPane, "PERSONA EDITA CON EXITO");
            personaEditar = null;
            limpiar();
        }

    }//GEN-LAST:event_btn_editarActionPerformed

    private void jButton_BuscarCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarCedulaActionPerformed

        Persona persona = controladorPersona.obtenerPersonCedula(txt_cedula.getText());
        if (persona != null) {
            txt_cedula.setText(persona.getCedula());
            txt_nombre.setText(persona.getNombre());
            txt_apellidos.setText(persona.getApellido());
            txt_direccion.setText(persona.getDireccion());
            txt_correo.setText(persona.getCorreo());
            txt_telefono.setText(persona.getTelefono());
        } else {
            JOptionPane.showMessageDialog(rootPane, "NO SE ENCONTRO AL USUARIO CON LA CEDULA ESPECIFICADA", "ERROR", JOptionPane.ERROR_MESSAGE);
            txt_cedula.setText(" ");
            txt_cedula.requestFocus();
        }
    }//GEN-LAST:event_jButton_BuscarCedulaActionPerformed

    private void jButton_BuscarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarTelefonoActionPerformed
        Persona persona = controladorPersona.obtenerPersonaTelefono(txt_telefono.getText());
        if (persona != null) {
            txt_cedula.setText(persona.getCedula());
            txt_nombre.setText(persona.getNombre());
            txt_apellidos.setText(persona.getApellido());
            txt_direccion.setText(persona.getDireccion());
            txt_correo.setText(persona.getCorreo());
            txt_telefono.setText(persona.getTelefono());
        } else {
            JOptionPane.showMessageDialog(rootPane, "NO SE ENCONTRO AL USUARIO CON EL NUMERO DE TELEFONO ESPECIFICADO", "ERROR", JOptionPane.ERROR_MESSAGE);
            txt_telefono.setText(" ");
            txt_telefono.requestFocus();
        }
    }//GEN-LAST:event_jButton_BuscarTelefonoActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        //ELIMINACION DE PERSONA:
        //CONDICION EN CASO DE QUE LOS CAMPOS ESTEN VACIOS:
        if (txt_cedula.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "ESPECIFIQUE QUE DESEA ELIMINAR", "ERROR", JOptionPane.ERROR_MESSAGE);
        //CASO CONTRARIO PASA A ELIMINAR LOS DATOS QUE SE ENCUENTREN EN LOS JTXTFIELS:
        } else {
            //MENSAJE DE CONFIRMACION CON SHOW CONFIRM DIALOG CON SI O NO:
            int confirmar = JOptionPane.showConfirmDialog(null, "¿ESTA SEGURO DE ELIMINAR A ESTE USUARIO?", "confirmar salida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            //EN CASO DE QUE LA OPCION SEA SI:
            if (confirmar == JOptionPane.YES_OPTION) {
                if (persona != null) {
                    //CONTROLADOR QUE SE ENCARGARGA DE ELIMINAR:
                    controladorPersona.eliminarPersona(persona);
                    JOptionPane.showMessageDialog(rootPane, "USUARIO SELECCIONADO ELIMINADO CON EXITO");
                    limpiar();
                }
            }
            //EN CASO DE QUE LA OPCION SEA NO: 
            if (confirmar == JOptionPane.NO_OPTION) {
                limpiar();
    }//GEN-LAST:event_btn_eliminarActionPerformed
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionPersonaV1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionPersonaV1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionPersonaV1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionPersonaV1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionPersonaV1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CuerpoRegistro;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_traer;
    private javax.swing.JButton jButton_BuscarCedula;
    private javax.swing.JButton jButton_BuscarTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_apellidos;
    private javax.swing.JLabel jLabel_cedula;
    private javax.swing.JLabel jLabel_correo;
    private javax.swing.JLabel jLabel_direccion;
    private javax.swing.JLabel jLabel_nombre;
    private javax.swing.JLabel jLabel_telefono;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
